apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-sa
      containers:
        - name: webapp
          image: narendran573/rosa-webapp:v1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/data
              name: webapp-storage
          envFrom:
            - configMapRef:
                name: webapp-config
            - secretRef:
                name: webapp-secret
      volumes:
        - name: webapp-storage
          persistentVolumeClaim:
            claimName: webapp-pvc
